steps:
# Build the numista-app container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-app'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/numista-app', '-f', 'Dockerfile', '.']

# Push the numista-app container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-app'
  args: ['push', 'gcr.io/$PROJECT_ID/numista-app']

# Deploy numista-app container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy-app'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'numista-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/numista-app'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/numista-app'
