/**
 * generate_report.js
 * Reads Playwright JSON results and generates a markdown morning report.
 * Run after: npx playwright test
 */

const fs = require('fs');
const path = require('path');

const RESULTS_FILE = path.join(__dirname, 'reports', 'test-results.json');
const REPORTS_DIR = path.join(__dirname, 'reports');
const SCREENSHOTS_DIR = path.join(__dirname, 'screenshots');

if (!fs.existsSync(RESULTS_FILE)) {
  console.error('No test-results.json found. Run tests first.');
  process.exit(1);
}

const results = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf8'));
const date = new Date().toISOString().split('T')[0];
const time = new Date().toLocaleTimeString('en-US', { hour12: false });
const reportFile = path.join(REPORTS_DIR, `${date}_morning_report.md`);

// Aggregate stats
let totalTests = 0;
let passed = 0;
let failed = 0;
let flaky = 0;
let skipped = 0;
const failures = [];
const warnings = [];

for (const suite of results.suites || []) {
  for (const spec of suite.specs || []) {
    for (const test of spec.tests || []) {
      totalTests++;
      const status = test.results?.[0]?.status;
      if (status === 'passed') passed++;
      else if (status === 'failed') {
        failed++;
        const errMsg = test.results?.[0]?.error?.message || 'Unknown error';
        const errStack = test.results?.[0]?.error?.stack?.split('\n')[0] || '';
        failures.push({
          suite: suite.title,
          test: spec.title,
          error: errMsg.substring(0, 300),
          duration: test.results?.[0]?.duration || 0,
        });
      }
      else if (status === 'flaky') flaky++;
      else if (status === 'skipped') skipped++;
    }
  }
}

const passRate = totalTests > 0 ? Math.round((passed / totalTests) * 100) : 0;
const statusEmoji = failed === 0 ? '✅' : failed <= 3 ? '⚠️' : '🚨';
const statusText = failed === 0 ? 'ALL CLEAR' : failed <= 3 ? 'MINOR ISSUES' : 'ATTENTION REQUIRED';

// Build markdown report
let report = `# ${statusEmoji} Numista.AI Automated Test Report
## ${statusText} — ${date} at ${time}

---

## Summary

| Metric | Value |
|--------|-------|
| **Total Tests** | ${totalTests} |
| **Passed** | ${passed} ✅ |
| **Failed** | ${failed} ${failed > 0 ? '❌' : ''} |
| **Flaky** | ${flaky} ${flaky > 0 ? '⚠️' : ''} |
| **Skipped** | ${skipped} |
| **Pass Rate** | ${passRate}% |

---

`;

if (failed === 0 && flaky === 0) {
  report += `## ✅ No Issues Found\n\nAll ${totalTests} tests passed. Numista.AI is operating normally.\n\n`;
} else {
  if (failed > 0) {
    report += `## ❌ Failed Tests (${failed})\n\n`;
    report += `> **Action Required**: Review and fix the following failures before your next deployment.\n\n`;
    for (const f of failures) {
      report += `### ${f.suite} > ${f.test}\n`;
      report += `- **Error**: \`${f.error}\`\n`;
      report += `- **Duration**: ${f.duration}ms\n\n`;
    }
  }
  if (flaky > 0) {
    report += `## ⚠️ Flaky Tests (${flaky})\n\nTests that passed on retry — may indicate intermittent issues.\n\n`;
  }
}

// Screenshot inventory
const screenshotFiles = fs.existsSync(SCREENSHOTS_DIR)
  ? fs.readdirSync(SCREENSHOTS_DIR).filter(f => f.endsWith('.png'))
  : [];

if (screenshotFiles.length > 0) {
  report += `## 📸 Screenshots Captured (${screenshotFiles.length})\n\n`;
  for (const f of screenshotFiles) {
    report += `- \`${f}\`\n`;
  }
  report += '\n';
}

report += `---\n\n## Test Suites Run\n\n`;
report += `| Suite | Tests | Status |\n|-------|-------|--------|\n`;
for (const suite of results.suites || []) {
  let suiteTotal = 0;
  let suitePassed = 0;
  for (const spec of suite.specs || []) {
    for (const t of spec.tests || []) {
      suiteTotal++;
      if (t.results?.[0]?.status === 'passed') suitePassed++;
    }
  }
  const suiteStatus = suiteTotal === suitePassed ? '✅ Pass' : `❌ ${suiteTotal - suitePassed} failed`;
  report += `| ${suite.title} | ${suiteTotal} | ${suiteStatus} |\n`;
}

report += `\n---\n\n_Generated by Numista.AI Automated Test Framework_\n_Site: https://numista.ai_\n`;

fs.writeFileSync(reportFile, report);
console.log(`\n✅ Morning report written to: ${reportFile}`);
console.log(`   Status: ${statusText}`);
console.log(`   Pass Rate: ${passRate}% (${passed}/${totalTests})`);
if (failed > 0) {
  console.log(`   ❌ ${failed} test(s) need attention!`);
  process.exit(1); // Non-zero exit signals failures to scheduler
}
