"""
feedback_miner.py — Numista QC Suite Layer 4
Mines feedback documents and classifies issues using Gemini API.
PII stripped before any output is written.
Degrades gracefully if LLM unavailable.

Output: staging/feedback_dynamic_{date}.spec.js (never auto-executed)
"""

import os
import sys
import re
import json
import datetime
from pathlib import Path

STAGING_DIR = Path(__file__).parent / 'staging'
STAGING_DIR.mkdir(exist_ok=True)

LLM_AVAILABLE = True

# ---------------------------------------------------------------------------
# PII filter — applied to all text before writing to any log or staging file
# ---------------------------------------------------------------------------
PII_PATTERNS = [
    r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',  # email
    r'\$[\d,]+(?:\.\d{2})?',                                    # dollar amounts
    r'\b(?:eric|seaman|jseaman)\w*\b',                          # name fragments
]

def strip_pii(text):
    for pattern in PII_PATTERNS:
        text = re.sub(pattern, '[REDACTED]', text, flags=re.IGNORECASE)
    return text


# ---------------------------------------------------------------------------
# Gemini classification
# ---------------------------------------------------------------------------
def classify_issues_with_gemini(raw_issues):
    """
    Classify a list of raw issue strings using the Gemini API.
    Returns a list of {category, description, priority} dicts.
    Degrades gracefully if LLM unavailable.
    """
    global LLM_AVAILABLE
    try:
        import google.generativeai as genai
        api_key = os.environ.get('GEMINI_API_KEY')
        if not api_key:
            raise RuntimeError('GEMINI_API_KEY not set')

        # Read model from SUITE_MANIFEST — never hardcode
        manifest_path = Path(__file__).parent.parent / 'SUITE_MANIFEST.json'
        with open(manifest_path) as f:
            manifest = json.load(f)
        model_id = manifest.get('synthesizer_model_id', 'gemini-2.0-flash-exp')

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(model_id)

        prompt = (
            "Classify each of the following user feedback issues into one of these categories: "
            "contrast_failure, title_display, navigation, data_integrity, performance, other. "
            "Return a JSON array of objects with fields: category, description, priority (1=critical, 3=low). "
            "Issues:\n" + "\n".join(f"- {strip_pii(i)}" for i in raw_issues)
        )

        response = model.generate_content(prompt)
        # Parse JSON from response
        text = response.text.strip()
        if text.startswith('```'):
            text = re.sub(r'^```[a-z]*\n?', '', text)
            text = re.sub(r'\n?```$', '', text)
        return json.loads(text)

    except Exception as e:
        LLM_AVAILABLE = False
        error_log = STAGING_DIR / f'synthesizer_errors_{datetime.date.today()}.log'
        with open(error_log, 'a') as f:
            f.write(f'[{datetime.datetime.now().isoformat()}] LLM_UNAVAILABLE: {e}\n')
        print(f'[feedback_miner] LLM_UNAVAILABLE: {e}. Falling back to keyword classification.')
        return _keyword_classify(raw_issues)


def _keyword_classify(raw_issues):
    """Keyword fallback classifier. Not used as primary."""
    results = []
    for issue in raw_issues:
        lower = issue.lower()
        if any(w in lower for w in ['contrast', 'color', 'white', 'dark', 'light']):
            cat = 'contrast_failure'
        elif any(w in lower for w in ['title', 'name', 'program', 'year', 'mint']):
            cat = 'title_display'
        elif any(w in lower for w in ['navigate', 'click', 'button', 'screen']):
            cat = 'navigation'
        else:
            cat = 'other'
        results.append({'category': cat, 'description': strip_pii(issue), 'priority': 2})
    return results


# ---------------------------------------------------------------------------
# Spec generator — writes to staging/ only
# ---------------------------------------------------------------------------
def generate_staging_spec(classified_issues):
    today = datetime.date.today().isoformat()
    spec_path = STAGING_DIR / f'feedback_dynamic_{today}.spec.js'

    lines = [
        f'// feedback_dynamic_{today}.spec.js — AUTO-GENERATED by feedback_miner.py',
        '// STAGING FILE: Never auto-executed. Human promotion required.',
        '// Generated: ' + datetime.datetime.now().isoformat(),
        '',
        "const { test, expect } = require('@playwright/test');",
        '',
    ]

    for issue in classified_issues:
        cat = issue.get('category', 'other')
        desc = issue.get('description', 'No description')[:120]
        priority = issue.get('priority', 2)
        safe_name = re.sub(r'[^a-zA-Z0-9 ]', '', desc)[:60].strip()
        lines += [
            f"test('[{cat}][p{priority}] {safe_name}', async ({{ page }}) => {{",
            f"  // Auto-generated from feedback. Review before promoting.",
            f"  // Category: {cat} | Priority: {priority}",
            f"  await page.goto('https://numista.ai');",
            f"  const pane = page.locator('flt-glass-pane');",
            f"  await expect(pane).toBeVisible();",
            f"  // TODO: add behavioral assertion for: {desc}",
            f"}});",
            '',
        ]

    with open(spec_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    return spec_path


def main():
    # Gather raw issues from any feedback files in the project
    feedback_sources = list(Path('..').glob('**/feedback_manifest*.json'))
    raw_issues = []

    for source in feedback_sources:
        try:
            with open(source) as f:
                data = json.load(f)
            if isinstance(data, list):
                raw_issues.extend(str(item) for item in data[:20])  # cap at 20 per file
            elif isinstance(data, dict):
                raw_issues.extend(str(v) for v in list(data.values())[:20])
        except Exception:
            continue

    if not raw_issues:
        print('[feedback_miner] No feedback sources found. Nothing to mine.')
        return

    print(f'[feedback_miner] Mining {len(raw_issues)} raw issues...')
    classified = classify_issues_with_gemini(raw_issues)

    spec_path = generate_staging_spec(classified)
    print(f'[feedback_miner] Staging spec written: {spec_path}')
    if not LLM_AVAILABLE:
        print('[feedback_miner] WARNING: LLM unavailable. Keyword fallback used. Review staging spec carefully.')
    print('[feedback_miner] Self-update: SKIPPED (LLM unavailable)' if not LLM_AVAILABLE else '[feedback_miner] Done.')


if __name__ == '__main__':
    main()
