import 'dart:math';
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/program_model.dart';
import '../utils/slot_resolver.dart';

/// Programs whose data is live/actively updated — show generation timestamp prominently.
const _activePrograms = {
  'American Innovation \$1 Coin Program',
  'American Women Quarters',
  'America the Beautiful Quarters (National Parks)',
  '2026 U.S. Circulating Coins',
  '2026 America250 - Circulating Currency',
  '2026 America250 - Numismatic Collectibles',
};

class ChecklistGeneratorService {
  /// Canonical Legal System of Record Estate Disclaimer
  static const String legalDisclaimer =
      'CONFIDENTIAL ESTATE & INVENTORY AUDIT RECORD. Generated by Numista.AI Legal System of Record engine. '
      'This snapshot reflects verified user collection holdings as of the UTC timestamp indicated. '
      'Values and grading references are for inventory valuation, safety deposit box reconciliation, and probate asset distribution purposes.';

  /// Sanitize strings for PDF Helvetica: replace characters outside Latin-1.
  static String _s(String? text) {
    if (text == null || text.isEmpty) return '';
    return text
        .replaceAll('\u2014', ' - ')  // em-dash
        .replaceAll('\u2013', '-')    // en-dash
        .replaceAll('\u2018', "'")    // left single quote
        .replaceAll('\u2019', "'")    // right single quote
        .replaceAll('\u201C', '"')    // left double quote
        .replaceAll('\u201D', '"')    // right double quote
        .replaceAll('\u2026', '...')  // ellipsis
        .replaceAll('\u2022', ' | ')  // bullet point
        .replaceAll('\u00A0', ' ');   // non-breaking space
  }

  /// Safely renders memory image bytes, falling back gracefully if image header fails to parse.
  static pw.Widget _buildSafeMemoryImage(Uint8List? bytes, {double? width, double? height}) {
    if (bytes == null || bytes.isEmpty) return pw.SizedBox();
    try {
      return pw.Image(pw.MemoryImage(bytes), width: width, height: height);
    } catch (e) {
      return pw.SizedBox();
    }
  }

  /// Lightweight vector checkbox rendered with pure pdf.Graphics paths.
  /// Renders clean vector square outline, and crisp vector checkmark if isOwned is true.
  static pw.Widget _buildVectorCheckbox({bool isOwned = false}) {
    return pw.Center(
      child: pw.Container(
        width: 11,
        height: 11,
        decoration: pw.BoxDecoration(
          border: pw.Border.all(
            color: isOwned ? PdfColors.blue800 : PdfColors.grey700,
            width: 0.8,
          ),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(1.5)),
          color: isOwned ? PdfColors.blue50 : null,
        ),
        child: isOwned
            ? pw.Center(
                child: pw.CustomPaint(
                  size: const PdfPoint(8, 8),
                  painter: (PdfGraphics canvas, PdfPoint size) {
                    canvas
                      ..setStrokeColor(PdfColors.blue800)
                      ..setLineWidth(1.2)
                      ..drawLine(1.5, 4.0, 3.5, 1.5)
                      ..drawLine(3.5, 1.5, 7.0, 6.5)
                      ..strokePath();
                  },
                ),
              )
            : null,
      ),
    );
  }

  /// Generates a dynamic PDF checklist for [program].
  /// Supports both Blank Master sheets and Personalized System of Record progress reports.
  static Future<Uint8List> generateChecklist(
    CoinProgram program, {
    Uint8List? logoBytes,
    Uint8List? edgeDiagramBytes,
    Map<String, Uint8List>? mintMarkDiagrams,
    Uint8List? ttfFontBytes,
    Uint8List? ttfBoldFontBytes,
    Map<String, SlotMatchResult>? resolvedInventory,
    String? collectorEmail,
    String? snapshotId,
    bool isPartialSnapshot = false,
    int? totalCatalogSlots,
    int? distinctOwnedSlots,
    int? totalOwnedItems,
  }) async {
    final now = DateTime.now().toUtc();
    final printDate = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
    final isActive = _activePrograms.contains(program.name);
    final isPersonalized = resolvedInventory != null && resolvedInventory.isNotEmpty;

    // ── Build Theme with custom UTF-8 TTF Font if provided ───────────────────
    pw.ThemeData? theme;
    if (ttfFontBytes != null && ttfFontBytes.isNotEmpty) {
      try {
        final ttf = pw.Font.ttf(ByteData.sublistView(ttfFontBytes));
        final ttfBold = (ttfBoldFontBytes != null && ttfBoldFontBytes.isNotEmpty)
            ? pw.Font.ttf(ByteData.sublistView(ttfBoldFontBytes))
            : ttf;
        theme = pw.ThemeData.withFont(base: ttf, bold: ttfBold);
      } catch (e) {
        // Fallback to default PDF font
      }
    }

    final pdf = pw.Document(
      title: _s('${program.name} Checklist'),
      author: 'Numista.AI System of Record',
    );

    // ── Defensive Guard: Empty Coins List ────────────────────────────────────
    if (program.coins.isEmpty) {
      pdf.addPage(
        pw.Page(
          theme: theme,
          pageFormat: PdfPageFormat.letter,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return pw.Center(
              child: pw.Column(
                mainAxisAlignment: pw.MainAxisAlignment.center,
                children: [
                  pw.Text('Numista.AI Official Program Checklist',
                      style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                  pw.SizedBox(height: 12),
                  pw.Text(_s(program.name.toUpperCase()),
                      style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 24),
                  pw.Text('No coin items are currently configured for this program.',
                      style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                ],
              ),
            );
          },
        ),
      );
      return pdf.save();
    }

    // ── Resolve diagram ───────────────────────────────────────────────────────
    final mmType = program.mintMarkType ?? '';
    final mmDesc = _s(program.mintMarkDescription);

    Uint8List? diagramBytes;
    if (mintMarkDiagrams != null && mmType.isNotEmpty) {
      diagramBytes = mintMarkDiagrams[mmType];
    } else if (edgeDiagramBytes != null && (mmType == 'EDGE' || mmType.isEmpty)) {
      diagramBytes = edgeDiagramBytes;
    }

    // Text color based on type
    PdfColor labelColor;
    switch (mmType) {
      case 'EDGE':   labelColor = PdfColors.red700; break;
      case 'MIXED':  labelColor = PdfColors.orange800; break;
      default:       labelColor = PdfColors.blue800;
    }

    // ── Determine layout: simple (1 variety/row) vs multi-column ─────────────
    final maxVarieties = program.coins.fold<int>(
      0, (m, c) => max(m, c.varieties.isEmpty ? 1 : c.varieties.length));
    final useSimpleLayout = maxVarieties <= 1;

    // ── Build variety columns for multi layout ────────────────────────────────
    final varietiesSet = <String>{};
    if (!useSimpleLayout) {
      for (var coin in program.coins) {
        for (var v in coin.varieties) { varietiesSet.add(v.id); }
      }
    }
    final vList = varietiesSet.toList();
    final order = ['P', 'D', 'W', 'O', 'CC', 'S', 'S-VDB', 'P-VDB', 'S-SILVER',
                   'S-PROOF', 'S-SATIN', 'SMS', 'P-PRIVY-JULY4', 'D-PRIVY-JULY4', 'S-REVERSE-PROOF'];
    vList.sort((a, b) {
      String baseA = a.replaceAll('-UNC', '');
      String baseB = b.replaceAll('-UNC', '');
      int idxA = order.indexOf(baseA); if (idxA == -1) idxA = 99;
      int idxB = order.indexOf(baseB); if (idxB == -1) idxB = 99;
      return idxA == idxB ? a.compareTo(b) : idxA.compareTo(idxB);
    });
    final varietyLabels = vList.map((id) => _s(ChecklistVariety.fromId(id).label)).toList();

    // ── Helper: coin label without duplicate year ────────────────────────────
    String coinLabel(ProgramCoin coin) {
      final yr  = coin.year ?? '';
      final nm  = _s(coin.name);
      if (yr.isEmpty) return nm;
      if (nm == yr || nm.startsWith(yr)) return nm;
      return '$yr - $nm';
    }

    // ── Table data builders ───────────────────────────────────────────────────
    List<dynamic> buildMultiRow(ProgramCoin coin, int rowIndex) {
      final row = <dynamic>[coinLabel(coin)];
      // Map variety id → ChecklistVariety so we can access .label for the Notes prefix.
      final coinVarietyMap = {for (final cv in coin.varieties) cv.id: cv};
      // Pairs of (varietyLabel, formattedNotes) for every owned variety in this row.
      final ownedNotes = <(String, String)>[];

      for (var vId in vList) {
        if (coinVarietyMap.containsKey(vId)) {
          final slotKey = '${program.id}_${coin.id}_$vId';
          final match = resolvedInventory?[slotKey];
          final isOwned = match != null && match.isOwned;
          row.add(_buildVectorCheckbox(isOwned: isOwned));

          if (isOwned && match.formattedNotes.isNotEmpty) {
            final label = coinVarietyMap[vId]!.label;
            ownedNotes.add((label, match.formattedNotes));
          }
        } else {
          row.add('');
        }
      }

      // Notes / QTY Column — labeled join (G3 Phase 1, OQ2).
      // One owned variety  → bare phrase, no label prefix (e.g. "3 loose (Raw)").
      // Multiple varieties → "P Unc: 3 loose (Raw) | D Unc: 2 loose (Raw) | S Proof: Raw".
      // ' | ' is used directly — unicode bullet \u2022 would be re-mapped by _s().
      final String notesText;
      if (ownedNotes.isEmpty) {
        notesText = '';
      } else if (ownedNotes.length == 1) {
        notesText = ownedNotes.first.$2;
      } else {
        notesText = ownedNotes.map((e) => '${e.$1}: ${e.$2}').join(' | ');
      }
      row.add(_s(notesText));
      return row;
    }

    // Progress metrics calculation
    final totalSlots = totalCatalogSlots ?? program.coins.fold<int>(0, (acc, c) => acc + (c.varieties.isEmpty ? 1 : c.varieties.length));
    final distinctOwned = distinctOwnedSlots ?? 0;
    final pct = totalSlots > 0 ? (distinctOwned / totalSlots * 100).toStringAsFixed(1) : '0.0';

    pdf.addPage(
      pw.MultiPage(
        theme: theme,
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.fromLTRB(20, 16, 20, 16),

        // ── Footer on all pages ───────────────────────────────────────────────
        footer: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                decoration: const pw.BoxDecoration(
                  border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
                ),
                padding: const pw.EdgeInsets.only(top: 2),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(_s(program.name.toUpperCase()),
                        style: const pw.TextStyle(fontSize: 7.0, color: PdfColors.grey600)),
                    pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
                        style: const pw.TextStyle(fontSize: 7.0, color: PdfColors.grey600)),
                    pw.Text('Printed UTC: $printDate ${snapshotId != null ? "($snapshotId)" : ""}',
                        style: const pw.TextStyle(fontSize: 7.0, color: PdfColors.grey600)),
                  ],
                ),
              ),
              if (isPersonalized) ...[
                pw.SizedBox(height: 1),
                pw.Text(
                  legalDisclaimer,
                  style: const pw.TextStyle(fontSize: 5.0, color: PdfColors.grey500),
                ),
              ],
            ],
          );
        },

        build: (pw.Context context) {
          return [
            // ── Header ─────────────────────────────────────────────────────
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Row(children: [
                    if (logoBytes != null) ...[
                      _buildSafeMemoryImage(logoBytes, width: 24, height: 24),
                      pw.SizedBox(width: 6),
                    ],
                    pw.Text(isPersonalized ? 'Numista.AI Collection Progress' : 'Numista.AI Checklist',
                        style: pw.TextStyle(
                            fontSize: 15,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.blue800)),
                  ]),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Generated UTC: $printDate',
                          style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey600)),
                      if (isActive)
                        pw.Text('* Active series - verified snapshot',
                            style: pw.TextStyle(fontSize: 7.0, color: PdfColors.orange700, fontStyle: pw.FontStyle.italic)),
                    ],
                  ),
                ],
              ),
            ),

            // ── Personalized Progress Header & Warning Badges ─────────────────
            if (isPersonalized) ...[
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  border: pw.Border.all(color: PdfColors.blue200),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(3)),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Collector: ${_s(collectorEmail ?? "Authenticated Owner")}',
                      style: pw.TextStyle(fontSize: 7.5, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900),
                    ),
                    pw.Text(
                      _s('Slots: $distinctOwned / $totalSlots ($pct%) • Total: ${totalOwnedItems ?? distinctOwned}'),
                      style: pw.TextStyle(fontSize: 7.5, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900),
                    ),
                    if (snapshotId != null)
                      pw.Text(
                        'ID: $snapshotId',
                        style: const pw.TextStyle(fontSize: 7.0, color: PdfColors.grey700),
                      ),
                  ],
                ),
              ),
              if (isPartialSnapshot) ...[
                pw.SizedBox(height: 2),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 2),
                  decoration: const pw.BoxDecoration(color: PdfColors.amber100),
                  child: pw.Text(
                    'WARNING: PARTIAL SNAPSHOT - Cloud collection sync incomplete.',
                    style: pw.TextStyle(fontSize: 6.5, fontWeight: pw.FontWeight.bold, color: PdfColors.brown900),
                  ),
                ),
              ],
              pw.SizedBox(height: 4),
            ] else ...[
              pw.SizedBox(height: 2),
            ],

            // ── Program title + years ───────────────────────────────────────
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(_s(program.name.toUpperCase()),
                    style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(width: 6),
                if (program.years.isNotEmpty)
                  pw.Text('(${_s(program.years)})',
                      style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
              ],
            ),
            if (program.category.isNotEmpty && program.category != 'Other')
              pw.Text('Category: ${_s(program.category)}',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey)),

            // ── Mint Mark Box ───────────────────────────────────────────────
            if (program.mintMarkLocations.isNotEmpty || mmDesc.isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Container(
                padding: const pw.EdgeInsets.all(5),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(3)),
                  color: PdfColors.grey50,
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    if (program.mintMarkLocations.isNotEmpty)
                      pw.Text(_s(program.mintMarkLocations),
                          style: pw.TextStyle(fontSize: 8.0, color: PdfColors.grey700, fontStyle: pw.FontStyle.italic)),
                    if (mmDesc.isNotEmpty) ...[
                      pw.SizedBox(height: 2),
                      pw.Row(
                        crossAxisAlignment: pw.CrossAxisAlignment.center,
                        children: [
                          pw.Expanded(
                            child: pw.Text(mmDesc,
                                style: pw.TextStyle(fontSize: 8.5, fontWeight: pw.FontWeight.bold, color: labelColor)),
                          ),
                          if (diagramBytes != null) ...[
                            pw.SizedBox(width: 8),
                            _buildSafeMemoryImage(diagramBytes, width: 110, height: 45),
                          ],
                        ],
                      ),
                    ],
                  ],
                ),
              ),
            ],

            pw.SizedBox(height: 4),
            pw.Text(
              isPersonalized
                  ? "Verified collection progress report. Checkmarks indicate authenticated items; 'Notes / QTY' lists verified grades and slabs."
                  : "Check off the coins you own. Use the 'Notes / QTY' column to record quantity (e.g. QTY:3) and grade (e.g. MS-65 or VF-30).",
              style: const pw.TextStyle(fontSize: 8.0, color: PdfColors.grey700),
            ),
            pw.SizedBox(height: 6),

            // ── Coin Table ──────────────────────────────────────────────────
            if (useSimpleLayout) ...[
              () {
                final pairs = <List<ProgramCoin>>[];
                for (int i = 0; i < program.coins.length; i += 2) {
                  pairs.add(program.coins.sublist(i, min(i + 2, program.coins.length)));
                }
                return pw.TableHelper.fromTextArray(
                  headers: [
                    'Year / Subject', 'Owned?', 'Notes / QTY',
                    'Year / Subject', 'Owned?', 'Notes / QTY',
                  ],
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8.5),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  cellHeight: 21,
                  cellPadding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 2),
                  columnWidths: {
                    0: const pw.FlexColumnWidth(3),
                    1: const pw.FixedColumnWidth(40),
                    2: const pw.FlexColumnWidth(1.6),
                    3: const pw.FlexColumnWidth(3),
                    4: const pw.FixedColumnWidth(40),
                    5: const pw.FlexColumnWidth(1.6),
                  },
                  cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    1: pw.Alignment.center,
                    2: pw.Alignment.centerLeft,
                    3: pw.Alignment.centerLeft,
                    4: pw.Alignment.center,
                    5: pw.Alignment.centerLeft,
                  },
                  data: pairs.map((pair) {
                    final coinA = pair[0];
                    final matchA = resolvedInventory?['${program.id}_${coinA.id}_P-UNC'] ??
                                   resolvedInventory?['${program.id}_${coinA.id}_'];
                    final isOwnedA = matchA != null && matchA.isOwned;

                    final row = <dynamic>[
                      coinLabel(coinA),
                      _buildVectorCheckbox(isOwned: isOwnedA),
                      _s(isOwnedA ? matchA.formattedNotes : ''),
                    ];
                    if (pair.length > 1) {
                      final coinB = pair[1];
                      final matchB = resolvedInventory?['${program.id}_${coinB.id}_P-UNC'] ??
                                     resolvedInventory?['${program.id}_${coinB.id}_'];
                      final isOwnedB = matchB != null && matchB.isOwned;
                      row.addAll([
                        coinLabel(coinB),
                        _buildVectorCheckbox(isOwned: isOwnedB),
                        _s(isOwnedB ? matchB.formattedNotes : ''),
                      ]);
                    } else {
                      row.addAll(['', '', '']);
                    }
                    return row;
                  }).toList(),
                );
              }(),
            ] else
              () {
                final hFont = vList.length >= 6 ? 7.0 : vList.length >= 4 ? 7.5 : 8.5;
                final maxLabelLen = program.coins.map((c) => coinLabel(c).length).fold<int>(0, max);
                final yrColW = (maxLabelLen * 5.2).clamp(90.0, 180.0);

                double colWidthFor(String id) {
                  if (id.length <= 2) return 22.0;
                  if (vList.length >= 6) return 32.0;
                  if (vList.length >= 4) return 38.0;
                  return 44.0;
                }

                return pw.TableHelper.fromTextArray(
                  headers: ['Year / Subject', ...varietyLabels, 'Notes / QTY'],
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: hFont),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  cellHeight: 21,
                  cellPadding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 2),
                  columnWidths: {
                    0: pw.FixedColumnWidth(yrColW),
                    for (int i = 1; i <= vList.length; i++)
                      i: pw.FixedColumnWidth(colWidthFor(vList[i - 1])),
                    vList.length + 1: const pw.FlexColumnWidth(1),
                  },
                  cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    for (int i = 1; i <= vList.length; i++) i: pw.Alignment.center,
                    vList.length + 1: pw.Alignment.centerLeft,
                  },
                  data: program.coins.asMap().entries
                      .map((e) => buildMultiRow(e.value, e.key))
                      .toList(),
                );
              }(),

            // ── Notes Block ─────────────────────────────────────────────────
            pw.SizedBox(height: 10),
            pw.Text('ADDITIONAL NOTES',
                style: pw.TextStyle(fontSize: 8.5, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700)),
            pw.SizedBox(height: 2),
            ...List.generate(3, (_) => pw.Column(
              children: [
                pw.SizedBox(height: 8),
                pw.Container(height: 0.5,
                    decoration: const pw.BoxDecoration(
                        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey400, width: 0.5)))),
              ],
            )),
          ];
        },
      ),
    );

    return pdf.save();
  }
}
