// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPGC879Tl1FaGucQmlw7qKL25b8v4ACF8',
    appId: '1:568985927038:web:9ea56548eed27d5a8b072f',
    messagingSenderId: '568985927038',
    projectId: 'studio-9101802118-8c9a8',
    authDomain: 'studio-9101802118-8c9a8.firebaseapp.com',
    storageBucket: 'studio-9101802118-8c9a8.firebasestorage.app',
    measurementId: 'G-EPZEHXZR5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSM3pQl0oWdZgOw2vXCvhyRH899l-ZvcM',
    appId: '1:568985927038:android:efb96a51420403078b072f',
    messagingSenderId: '568985927038',
    projectId: 'studio-9101802118-8c9a8',
    storageBucket: 'studio-9101802118-8c9a8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUUhn2lp5mSalBlIxMcvveRzxPtiC9O2k',
    appId: '1:568985927038:web:14e303f30991f9e78b072f',
    messagingSenderId: '568985927038',
    projectId: 'studio-9101802118-8c9a8',
    authDomain: 'studio-9101802118-8c9a8.firebaseapp.com',
    storageBucket: 'studio-9101802118-8c9a8.firebasestorage.app',
    measurementId: 'G-7R4F1W3Q03',
  );
}
