import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

new_mobile = (
    "              // Two Columns Layout - stacks on mobile\n"
    "              if (isMobile) ...[\n"
    "                const Text('Analytics Message Board',\n"
    "                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.w600, color: Color(0xFF31333F))),\n"
    "                const SizedBox(height: 12),\n"
    "                Container(\n"
    "                  padding: const EdgeInsets.all(16.0),\n"
    "                  decoration: BoxDecoration(\n"
    "                    color: Colors.white,\n"
    "                    border: Border.all(color: const Color(0xFFE2E6E9)),\n"
    "                    borderRadius: BorderRadius.circular(8),\n"
    "                  ),\n"
    "                  child: Column(\n"
    "                    crossAxisAlignment: CrossAxisAlignment.start,\n"
    "                    children: [\n"
    "                      const Text('Recently Added Coins:', style: TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF31333F))),\n"
    "                      const SizedBox(height: 12),\n"
    "                      Table(\n"
    "                        border: TableBorder(horizontalInside: BorderSide(color: Colors.grey.shade200)),\n"
    "                        columnWidths: const {0: FlexColumnWidth(1), 1: FlexColumnWidth(2), 2: FlexColumnWidth(1.5)},\n"
    "                        children: [\n"
    "                          _buildTableRow('Year', 'Denom.', 'Est. Value', isHeader: true),\n"
    "                          ...last5.map((doc) {\n"
    "                            final data = doc.data() as Map<String, dynamic>;\n"
    "                            return _buildTableRow(\n"
    "                              data['Year']?.toString() ?? '????',\n"
    "                              data['Denomination']?.toString() ?? 'Unknown',\n"
    "                              data['AI Estimated Value']?.toString() ?? '--',\n"
    "                            );\n"
    "                          }),\n"
    "                          if (last5.isEmpty) _buildTableRow('', 'No coins found', ''),\n"
    "                        ],\n"
    "                      ),\n"
    "                    ],\n"
    "                  ),\n"
    "                ),\n"
    "                const SizedBox(height: 24),\n"
    "                const Text('AI Numismatic Deepdive',\n"
    "                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.w600, color: Color(0xFF31333F))),\n"
    "                const SizedBox(height: 12),\n"
    "                Container(\n"
    "                  padding: const EdgeInsets.all(16.0),\n"
    "                  decoration: BoxDecoration(\n"
    "                    color: const Color(0xFFF8F9FB),\n"
    "                    border: Border.all(color: const Color(0xFFE2E6E9)),\n"
    "                    borderRadius: BorderRadius.circular(8),\n"
    "                  ),\n"
    "                  child: Column(\n"
    "                    crossAxisAlignment: CrossAxisAlignment.start,\n"
    "                    children: [\n"
    "                      const Text('Suggested Questions:', style: TextStyle(color: Color(0xFF5A5C69), fontSize: 12)),\n"
    "                      const SizedBox(height: 12),\n"
    "                      Wrap(\n"
    "                        spacing: 8, runSpacing: 8,\n"
    "                        children: [\n"
    "                          _buildSuggestionPill('Most Valuable?', onTap: () => _askDeepDive('What is my most valuable coin?')),\n"
    "                          _buildSuggestionPill('Coins from 2025?', onTap: () => _askDeepDive('Show me my coins purchased in 2025')),\n"
    "                          _buildSuggestionPill('Next Purchase?', onTap: () => _askDeepDive('What should I add next to my collection?')),\n"
    "                        ],\n"
    "                      ),\n"
    "                      const SizedBox(height: 16),\n"
    "                      if (_messages.isNotEmpty)\n"
    "                        Container(\n"
    "                          constraints: const BoxConstraints(maxHeight: 300),\n"
    "                          margin: const EdgeInsets.only(bottom: 12),\n"
    "                          child: ListView.builder(\n"
    "                            shrinkWrap: true,\n"
    "                            itemCount: _messages.length + (_isDeepDiving ? 1 : 0),\n"
    "                            itemBuilder: (ctx, i) {\n"
    "                              if (_isDeepDiving && i == _messages.length) {\n"
    "                                return Align(alignment: Alignment.centerLeft,\n"
    "                                  child: Container(\n"
    "                                    margin: const EdgeInsets.only(top: 8, bottom: 4),\n"
    "                                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "                                    decoration: BoxDecoration(color: const Color(0xFFF0F4FF), borderRadius: BorderRadius.circular(12)),\n"
    "                                    child: const SizedBox(width: 40, height: 16,\n"
    "                                      child: LinearProgressIndicator(color: Color(0xFF3B82F6), backgroundColor: Color(0xFFBFD0FB)))));\n"
    "                              }\n"
    "                              final msg = _messages[i];\n"
    "                              final isUser = msg['role'] == 'user';\n"
    "                              return Align(\n"
    "                                alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,\n"
    "                                child: Container(\n"
    "                                  margin: const EdgeInsets.only(top: 6, bottom: 4),\n"
    "                                  padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "                                  constraints: const BoxConstraints(maxWidth: 340),\n"
    "                                  decoration: BoxDecoration(\n"
    "                                    color: isUser ? const Color(0xFFF63366) : Colors.white,\n"
    "                                    borderRadius: BorderRadius.circular(12),\n"
    "                                    border: isUser ? null : Border.all(color: const Color(0xFFE2E6E9)),\n"
    "                                  ),\n"
    "                                  child: Text(msg['content'] ?? '',\n"
    "                                    style: TextStyle(fontSize: 13, color: isUser ? Colors.white : const Color(0xFF31333F))),\n"
    "                                ),\n"
    "                              );\n"
    "                            },\n"
    "                          ),\n"
    "                        ),\n"
    "                      Container(\n"
    "                        padding: const EdgeInsets.symmetric(horizontal: 12.0),\n"
    "                        decoration: BoxDecoration(\n"
    "                          color: Colors.white,\n"
    "                          borderRadius: BorderRadius.circular(24),\n"
    "                          border: Border.all(color: const Color(0xFFE2E6E9)),\n"
    "                        ),\n"
    "                        child: Row(children: [\n"
    "                          Expanded(child: TextField(\n"
    "                            controller: _searchController,\n"
    "                            style: const TextStyle(color: Color(0xFF31333F)),\n"
    "                            decoration: const InputDecoration(hintText: 'Ask about your collection...', hintStyle: TextStyle(color: Color(0xFFA0A3AB)), border: InputBorder.none),\n"
    "                            onSubmitted: (val) => _askDeepDive(val),\n"
    "                          )),\n"
    "                          IconButton(\n"
    "                            icon: Icon(Icons.send, color: _isDeepDiving ? Colors.grey : const Color(0xFFF63366)),\n"
    "                            onPressed: _isDeepDiving ? null : () => _askDeepDive(_searchController.text),\n"
    "                          ),\n"
    "                        ]),\n"
    "                      ),\n"
    "                    ],\n"
    "                  ),\n"
    "                ),\n"
    "              ] else Row(\n"
)

with open('lib/screens/home_dashboard.dart', encoding='utf-8') as f:
    lines = f.readlines()

# lines 432-610 (1-indexed) = indices 431-609 (0-indexed)
before = lines[:431]
after = lines[610:]

new_lines = before + [new_mobile] + after

with open('lib/screens/home_dashboard.dart', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f'Done. New file has {len(new_lines)} lines.')
