import 'package:flutter/material.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  static const _bg      = Color(0xFFF0F2F6);
  static const _surface = Colors.white;
  static const _blue    = Color(0xFF1565C0);
  static const _text    = Color(0xFF0F172A);
  static const _sub     = Color(0xFF64748B);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _bg,
      appBar: AppBar(
        title: const Text(
          'Terms of Use',
          style: TextStyle(
            color: _text,
            fontWeight: FontWeight.bold,
            fontSize: 20,
          ),
        ),
        backgroundColor: _surface,
        elevation: 0,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.close_rounded, color: _text),
          onPressed: () => Navigator.of(context).pop(),
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(color: const Color(0xFFE2E8F0), height: 1),
        ),
      ),
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 680),
            child: Container(
              margin: const EdgeInsets.all(16),
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: _surface,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: const Color(0xFFCBD5E1)),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withAlpha(5),
                    blurRadius: 10,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: const SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Numista.AI Terms of Use',
                      style: TextStyle(
                        color: _text,
                        fontSize: 22,
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    SizedBox(height: 6),
                    Text(
                      'Last updated: May 24, 2026',
                      style: TextStyle(color: _sub, fontSize: 13),
                    ),
                    Divider(height: 32, color: Color(0xFFE2E8F0)),
                    
                    Text(
                      'Welcome to Numista.AI. By using our mobile or web application, you agree to comply with and be bound by the following Terms of Use. Please review them carefully.',
                      style: TextStyle(color: _text, fontSize: 14, height: 1.5),
                    ),
                    SizedBox(height: 20),

                    _SectionHeader(title: '1. Use of the Service'),
                    _BulletPoint(
                      boldText: 'Eligibility: ',
                      text: 'You must be at least 13 years of age to use this service.',
                    ),
                    _BulletPoint(
                      boldText: 'Account Credentials: ',
                      text: 'You are responsible for maintaining the confidentiality of your email and PIN. All activities performed under your account are your sole responsibility.',
                    ),
                    _BulletPoint(
                      boldText: 'Acceptable Use: ',
                      text: 'You agree not to use the application for any unlawful purpose or to upload any harmful, offensive, or copyright-infringing content.',
                    ),
                    SizedBox(height: 20),

                    _SectionHeader(title: '2. Intellectual Property'),
                    _BulletPoint(
                      boldText: 'Our Property: ',
                      text: 'All designs, branding, source code, and algorithms are proprietary to Numista.AI and protected by international trademark and copyright laws.',
                    ),
                    _BulletPoint(
                      boldText: 'User Content: ',
                      text: 'You retain all ownership rights to any coin data, notes, and photos you upload. By uploading them, you grant us a standard license to display and store them to provide the services to you.',
                    ),
                    SizedBox(height: 20),

                    _SectionHeader(title: '3. AI Estimations & Financial Disclaimer'),
                    _BulletPoint(
                      boldText: 'Educational Purposes: ',
                      text: 'All coin grades, classifications, and price estimations are generated by automated algorithms and community inputs for informational and educational purposes only.',
                    ),
                    _BulletPoint(
                      boldText: 'No Financial Advice: ',
                      text: 'These estimations do not constitute formal financial, investment, or certified numismatic grading advice. You should consult certified grading houses (such as PCGS or NGC) before buying or selling high-value items.',
                    ),
                    SizedBox(height: 20),

                    _SectionHeader(title: '4. Limitation of Liability'),
                    Text(
                      'To the maximum extent permitted by law, Numista.AI, its founders, and contributors shall not be liable for any direct, indirect, special, incidental, or consequential damages resulting from your reliance on coin valuation data or your use of the application.',
                      style: TextStyle(color: _text, fontSize: 14, height: 1.5),
                    ),
                    SizedBox(height: 20),

                    _SectionHeader(title: '5. Service Termination'),
                    Text(
                      'We reserve the right to suspend or terminate your account or access to the service at our sole discretion, without prior notice, if we believe your conduct violates these Terms, is harmful to other users, or disrupts our operations.',
                      style: TextStyle(color: _text, fontSize: 14, height: 1.5),
                    ),
                    SizedBox(height: 20),

                    _SectionHeader(title: '6. Governing Law'),
                    Text(
                      'These Terms of Use shall be governed by and construed in accordance with the laws of the jurisdiction where the project founders reside, without regard to conflict of law rules.',
                      style: TextStyle(color: _text, fontSize: 14, height: 1.5),
                    ),
                    SizedBox(height: 28),

                    Divider(height: 1, color: Color(0xFFE2E8F0)),
                    SizedBox(height: 20),
                    Text(
                      'Questions or Concerns',
                      style: TextStyle(
                        color: _text,
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(height: 6),
                    Text(
                      'If you have any questions about these Terms of Use, please contact us at support@numista.ai.',
                      style: TextStyle(color: _sub, fontSize: 13, height: 1.4),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class _SectionHeader extends StatelessWidget {
  final String title;
  const _SectionHeader({required this.title});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Text(
        title,
        style: const TextStyle(
          color: TermsScreen._blue,
          fontSize: 16,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }
}

class _BulletPoint extends StatelessWidget {
  final String boldText;
  final String text;
  const _BulletPoint({required this.boldText, required this.text});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(left: 12, bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Padding(
            padding: EdgeInsets.only(top: 6, right: 8),
            child: Icon(Icons.circle, size: 5, color: TermsScreen._sub),
          ),
          Expanded(
            child: RichText(
              text: TextSpan(
                style: const TextStyle(color: TermsScreen._text, fontSize: 14, height: 1.4),
                children: [
                  TextSpan(
                    text: boldText,
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                  TextSpan(text: text),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
